// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsHogskoleprovet = {
  hogskoleprovetSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsHogskoleprovet;
