// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsSprak = {
  sprakSidebar: [
    'glosor',
    {
      type: 'category',
      label: 'Italienska',
      collapsed: true,
      items: [
    'italienska/intro',
    'italienska/ordabok',
    'italienska/anteckningar',
    {
      type: 'category',
      label: 'Övningar',
      collapsed: true,
      items: ['italienska/ovningar/verbovning'],
    },
    {
      type: 'category',
      label: 'Grammatik',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '👋 Introduktion',
          collapsed: true,
          items: ['italienska/grammatik/index', 'italienska/grammatik/acknowledgements'],
        },
        {
          type: 'category',
          label: '🔤 Grunder & uttal',
          items: [
            'italienska/grammatik/basics/alphabet',
            'italienska/grammatik/basics/pronunciation',
            'italienska/grammatik/basics/stress',
            'italienska/grammatik/basics/spelling',
          ],
        },
        {
          type: 'category',
          label: '⚡ Verb',
          items: [
            'italienska/grammatik/verbs/verb-intro',
            'italienska/grammatik/verbs/present-tense',
            'italienska/grammatik/verbs/regular-verbs',
            'italienska/grammatik/verbs/essere-avere',
            'italienska/grammatik/verbs/irregular-verbs',
            'italienska/grammatik/verbs/modal-verbs',
            'italienska/grammatik/verbs/reflexive-verbs',
            'italienska/grammatik/verbs/passato-prossimo',
            'italienska/grammatik/verbs/imperfetto',
            'italienska/grammatik/verbs/passato-remoto',
            'italienska/grammatik/verbs/trapassato',
            'italienska/grammatik/verbs/future',
            'italienska/grammatik/verbs/conditional',
            'italienska/grammatik/verbs/imperative',
            'italienska/grammatik/verbs/subjunctive',
            'italienska/grammatik/verbs/gerund-progressive',
            'italienska/grammatik/verbs/passive',
          ],
        },
        {
          type: 'category',
          label: '📦 Substantiv',
          items: [
            'italienska/grammatik/nouns/noun-intro',
            'italienska/grammatik/nouns/gender',
            'italienska/grammatik/nouns/plural',
            'italienska/grammatik/nouns/definite-article',
            'italienska/grammatik/nouns/indefinite-article',
            'italienska/grammatik/nouns/irregular-nouns',
            'italienska/grammatik/nouns/suffixes',
          ],
        },
        {
          type: 'category',
          label: '🎨 Adjektiv',
          items: [
            'italienska/grammatik/adjectives/adjective-intro',
            'italienska/grammatik/adjectives/agreement',
            'italienska/grammatik/adjectives/position',
            'italienska/grammatik/adjectives/comparison',
            'italienska/grammatik/adjectives/bello-buono-grande',
          ],
        },
        {
          type: 'category',
          label: '👥 Pronomen',
          items: [
            'italienska/grammatik/pronouns/pronoun-intro',
            'italienska/grammatik/pronouns/subject-pronouns',
            'italienska/grammatik/pronouns/direct-object',
            'italienska/grammatik/pronouns/indirect-object',
            'italienska/grammatik/pronouns/combined-pronouns',
            'italienska/grammatik/pronouns/ci-ne',
            'italienska/grammatik/pronouns/relative',
            'italienska/grammatik/pronouns/indefinite',
          ],
        },
        {
          type: 'category',
          label: '📍 Prepositioner',
          items: [
            'italienska/grammatik/prepositions/preposition-intro',
            'italienska/grammatik/prepositions/di-a-da',
            'italienska/grammatik/prepositions/in-con-su-per-tra',
            'italienska/grammatik/prepositions/articulated',
            'italienska/grammatik/prepositions/verbs-with-prepositions',
            'italienska/grammatik/prepositions/time-place',
          ],
        },
        {
          type: 'category',
          label: '🚀 Adverb',
          items: [
            'italienska/grammatik/adverbs/adverb-intro',
            'italienska/grammatik/adverbs/formation',
            'italienska/grammatik/adverbs/position',
          ],
        },
        {
          type: 'category',
          label: '🧩 Syntax',
          items: [
            'italienska/grammatik/syntax/syntax-intro',
            'italienska/grammatik/syntax/word-order',
            'italienska/grammatik/syntax/questions',
            'italienska/grammatik/syntax/negation',
            'italienska/grammatik/syntax/subordinate-clauses',
            'italienska/grammatik/syntax/conjunctions',
            'italienska/grammatik/syntax/si-constructions',
          ],
        },
        {
          type: 'category',
          label: '🔊 Ljudförändringar',
          items: [
            'italienska/grammatik/sound-changes/spelling-changes',
            'italienska/grammatik/sound-changes/elision-truncation',
          ],
        },
        {
          type: 'category',
          label: '📚 Referens',
          items: [
            'italienska/grammatik/reference/irregular-verbs-list',
            'italienska/grammatik/reference/conjugation-tables',
            'italienska/grammatik/reference/glossary',
          ],
        },
      ],
    },
      ],
    },
    {
      type: 'category',
      label: 'Spanska',
      collapsed: true,
      items: [
    'spanska/intro',
    'spanska/ordabok',
    'spanska/anteckningar',
    {
      type: 'category',
      label: 'Övningar',
      collapsed: true,
      items: ['spanska/ovningar/verbovning'],
    },
      ],
    },
    {
      type: 'category',
      label: 'Tyska',
      collapsed: true,
      items: [
    'tyska/intro',
    'tyska/ordabok',
    'tyska/anteckningar',
    {
      type: 'category',
      label: 'Övningar',
      collapsed: true,
      items: ['tyska/ovningar/konjugationsovning', 'tyska/ovningar/deklinationsovning'],
    },
    {
      type: 'category',
      label: 'Grammatik',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '👋 Introduktion',
          collapsed: true,
          items: ['tyska/grammatik/index', 'tyska/grammatik/acknowledgements'],
        },
        {
          type: 'category',
          label: '🔤 Grunderna & uttal',
          items: [
            'tyska/grammatik/basics/alphabet',
            'tyska/grammatik/basics/pronunciation',
            'tyska/grammatik/basics/stress',
            'tyska/grammatik/basics/spelling',
          ],
        },
        {
          type: 'category',
          label: '⚡ Verb',
          items: [
            'tyska/grammatik/verbs/verb-intro',
            'tyska/grammatik/verbs/present-tense',
            'tyska/grammatik/verbs/weak-verbs',
            'tyska/grammatik/verbs/strong-verbs',
            'tyska/grammatik/verbs/sein-haben-werden',
            'tyska/grammatik/verbs/modal-verbs',
            'tyska/grammatik/verbs/separable-verbs',
            'tyska/grammatik/verbs/perfect-tense',
            'tyska/grammatik/verbs/simple-past',
            'tyska/grammatik/verbs/past-perfect',
            'tyska/grammatik/verbs/future',
            'tyska/grammatik/verbs/imperative',
            'tyska/grammatik/verbs/subjunctive-2',
            'tyska/grammatik/verbs/subjunctive-1',
            'tyska/grammatik/verbs/passive',
            'tyska/grammatik/verbs/reflexive-verbs',
            'tyska/grammatik/verbs/infinitive-clauses',
            'tyska/grammatik/verbs/verb-government',
            'tyska/grammatik/verbs/verbs-with-prepositions',
          ],
        },
        {
          type: 'category',
          label: '📦 Substantiv',
          items: [
            'tyska/grammatik/nouns/noun-intro',
            'tyska/grammatik/nouns/gender',
            'tyska/grammatik/nouns/plural',
            'tyska/grammatik/nouns/cases',
            'tyska/grammatik/nouns/articles',
            'tyska/grammatik/nouns/weak-nouns',
            'tyska/grammatik/nouns/compound-nouns',
          ],
        },
        {
          type: 'category',
          label: '🎨 Adjektiv',
          items: [
            'tyska/grammatik/adjectives/adjective-intro',
            'tyska/grammatik/adjectives/declension',
            'tyska/grammatik/adjectives/comparison',
            'tyska/grammatik/adjectives/adjectival-nouns',
            'tyska/grammatik/adjectives/participles',
            'tyska/grammatik/adjectives/adjectives-with-prepositions',
          ],
        },
        {
          type: 'category',
          label: '👥 Pronomen',
          items: [
            'tyska/grammatik/pronouns/pronoun-intro',
            'tyska/grammatik/pronouns/personal',
            'tyska/grammatik/pronouns/possessive',
            'tyska/grammatik/pronouns/reflexive',
            'tyska/grammatik/pronouns/demonstrative',
            'tyska/grammatik/pronouns/relative',
            'tyska/grammatik/pronouns/interrogative',
            'tyska/grammatik/pronouns/indefinite',
          ],
        },
        {
          type: 'category',
          label: '📍 Prepositioner',
          items: [
            'tyska/grammatik/prepositions/preposition-intro',
            'tyska/grammatik/prepositions/accusative',
            'tyska/grammatik/prepositions/dative',
            'tyska/grammatik/prepositions/two-way',
            'tyska/grammatik/prepositions/genitive',
            'tyska/grammatik/prepositions/contractions',
          ],
        },
        {
          type: 'category',
          label: '🚀 Adverb',
          items: [
            'tyska/grammatik/adverbs/adverb-intro',
            'tyska/grammatik/adverbs/types',
            'tyska/grammatik/adverbs/modal-particles',
          ],
        },
        {
          type: 'category',
          label: '🔢 Räkneord & tid',
          items: [
            'tyska/grammatik/numbers/cardinal-numbers',
            'tyska/grammatik/numbers/ordinals-dates',
            'tyska/grammatik/numbers/time',
          ],
        },
        {
          type: 'category',
          label: '🧩 Syntax',
          items: [
            'tyska/grammatik/syntax/syntax-intro',
            'tyska/grammatik/syntax/main-clauses',
            'tyska/grammatik/syntax/questions',
            'tyska/grammatik/syntax/subordinate-clauses',
            'tyska/grammatik/syntax/conjunctions',
            'tyska/grammatik/syntax/negation',
            'tyska/grammatik/syntax/word-order',
            'tyska/grammatik/syntax/commas',
          ],
        },
        {
          type: 'category',
          label: '🔊 Ljudförändringar',
          items: ['tyska/grammatik/sound-changes/umlaut', 'tyska/grammatik/sound-changes/ablaut'],
        },
        {
          type: 'category',
          label: '📚 Referens',
          items: [
            'tyska/grammatik/reference/strong-verbs-list',
            'tyska/grammatik/reference/declension-tables',
            'tyska/grammatik/reference/glossary',
          ],
        },
      ],
    },
      ],
    },
  ],
};

export default sidebarsSprak;